### ISSUE TITLE
The plugin file could not be found

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [gatewayd-io/gatewayd-plugin-cache#63]
after executing this line 
_./gatewayd plugin install https://github.com/gatewayd-io/gatewayd-plugin-cache@v0.2.4_
I get this error
**2023/09/15 13:25:14 The plugin file could not be found**

**Comment by mostafa** [comment]
Hey @ebrahimkhodadadi,

Are you using Windows? Because the plugin only supports Linux and macOS at the moment.

**Comment by ebrahimkhodadadi** [comment]
I used to run in WSL2

**Comment by mostafa** [comment]
Remove the `https://` from the URL, as I also mentioned [here](https://docs.gatewayd.io/getting-started/installation/#installing-plugins) in the docs and try again. Also, use the latest version of GatewayD and the plugin.
